name: oauth2discord

services:
  postgres:
    image: postgres:16
    container_name: discordoauth-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oauth2discord
    volumes:
      - discordoauth:/postgresql/data

  redis:
    image: redis:7
    container_name: discordoauth-redis
    ports:
      - 6379:6379


volumes:
  discordoauth: